# These are supported funding model platforms

# github: # your-github-username
# patreon: # your-patreon-username
# open_collective: # your-open-collective-username
# ko_fi: # your-ko-fi-username
# custom: # your-custom-link

