include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Enforce best practices
    avoid_print: true
    prefer_const_constructors: true
    always_use_package_imports: true
    
    # Additional strict rules
    prefer_single_quotes: true
    sort_constructors_first: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_await_in_return: true
    use_super_parameters: true
    
    # Performance
    avoid_slow_async_io: true
    
    # Style
    require_trailing_commas: true
    directives_ordering: true
